limits-service:
  minimum: 99
  maximum: 9999

---

spring:
  profiles: dev

limits-service:
  minimum: 100
  maximum: 1000


---

spring:
  profiles: qa

limits-service:
  minimum: 222
  maximum: 2222